apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-service
spec:
  minReplicas: 3
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
