server:
  port: 5002
  
spring:
  application:
    name: consumer-service
  cloud:
    config:
      enabled: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/telemetry
    username: admin
    password: Admin123
    pool:
      initial-size: 5
      max-size: 20
  # Optional, for schema initialization
  sql:
    init:
      mode: always

redis:
  uri: redis://:Test321redis$@localhost:6379    

kafka:
  bootstrap:
    # Kafka broker addresses (comma-separated for multiple brokers)
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}  # default to localhost
  username: ${KAFKA_USERNAME:} # empty by default
  password: ${KAFKA_PASSWORD:} # empty by default
  security:
    # Security protocol to use
    # PLAINTEXT       -> no auth (dev/local)
    # SASL_PLAINTEXT  -> SASL authentication over plaintext
    # SASL_SSL        -> SASL authentication over SSL/TLS
    # SSL             -> SSL/TLS encryption without SASL auth
    protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT} # default PLAINTEXT
    sasl:
      # SASL mechanism (used only if protocol is SASL_PLAINTEXT or SASL_SSL)
      # Options:
      # SCRAM-SHA-256
      # SCRAM-SHA-512
      # PLAIN
      # GSSAPI (Kerberos)
      mechanism: ${KAFKA_SASL_MECHANISM:} # PLAIN by default
  topic: ingestion-topic
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway,refresh
  tracing:
    sampling:
      # Trace 100% of requests in dev; reduce in prod
      probability: 0.2
  otlp:
    tracing:
      enabled: false
      # OTLP collector endpoint (gRPC)
      #endpoint: http://localhost:4317
    otlp:
    metrics:
      export:
        enabled: false
      

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [${spring.application.name:}, traceId=%X{traceId:-}, spanId=%X{spanId:-}] [%logger{0}.%M:%L] - %msg%n"
  level:
    root: INFO
    com.telemetry.engine: DEBUG 
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG