spring:
  application:
    name: query-service

  config:
    import: >
      classpath:asset-metadata.yaml,
      optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    config:
      fail-fast: true